version: '3.8'

services:
  web:
    build: ./app
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:6
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
